#!/usr/bin/env bash
# It is important that this script does not echo to stdout
# Emacs `message-send-mail-with-sendmail` fails when
# stdout is non-empty
set -e
set -o pipefail


QUEUE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/mail.queue"
LOG="${XDG_LOG_HOME:-$HOME/.local/log}/msmtpq.log"

msg() {
    m="$(date -Iseconds) $1"
    echo "$m" >> "${LOG}"
}

msg "msmtpq: Starting with args $*"

[[ -d "$QUEUE_DIR" ]] || mkdir -m0700 -p "$QUEUE_DIR"

if [[ ! -w "$QUEUE_DIR" ]]; then
    msg "Insufficient privileges to write to queue."
    exit 1
fi

TMP_DIR=$(mktemp -d "$QUEUE_DIR/.tmpXXXXXXXXXX")
bail() {
    ret="$?"
    if [[ "$ret" -eq 0 ]]; then
        msg "Canceled: Not queuing message."
    fi
    rm -rf "$TMP_DIR"
}
trap bail EXIT

printf '%s\0' "$@" > "$TMP_DIR/msmtp_flags"
cat > "$TMP_DIR/message"

while [[ -d "$TMP_DIR" ]]; do
    MESSAGE_DIR="$(date +"$HOSTNAME-%s%N-P$$.mail")"
    #
    # Atomic rename.
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # must use gnu mv for -T
       gmv -n -T "$TMP_DIR" "$QUEUE_DIR/$MESSAGE_DIR"
    else
       mv -n -T "$TMP_DIR" "$QUEUE_DIR/$MESSAGE_DIR"
    fi
done

msg "done: Queued in dir ${MESSAGE_DIR}"
trap - EXIT
